export const API_V1_CATEGORY_LIST = "API_V1_CATEGORY_LIST"
export const API_V1_CATEGORY_LIST_SUCCEEDED = "API_V1_CATEGORY_LIST_SUCCEEDED"
export const API_V1_CATEGORY_LIST_FAILED = "API_V1_CATEGORY_LIST_FAILED"
export const API_V1_CATEGORY_CREATE = "API_V1_CATEGORY_CREATE"
export const API_V1_CATEGORY_CREATE_SUCCEEDED =
  "API_V1_CATEGORY_CREATE_SUCCEEDED"
export const API_V1_CATEGORY_CREATE_FAILED = "API_V1_CATEGORY_CREATE_FAILED"
export const API_V1_CATEGORY_READ = "API_V1_CATEGORY_READ"
export const API_V1_CATEGORY_READ_SUCCEEDED = "API_V1_CATEGORY_READ_SUCCEEDED"
export const API_V1_CATEGORY_READ_FAILED = "API_V1_CATEGORY_READ_FAILED"
export const API_V1_CATEGORY_UPDATE = "API_V1_CATEGORY_UPDATE"
export const API_V1_CATEGORY_UPDATE_SUCCEEDED =
  "API_V1_CATEGORY_UPDATE_SUCCEEDED"
export const API_V1_CATEGORY_UPDATE_FAILED = "API_V1_CATEGORY_UPDATE_FAILED"
export const API_V1_CATEGORY_PARTIAL_UPDATE = "API_V1_CATEGORY_PARTIAL_UPDATE"
export const API_V1_CATEGORY_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_CATEGORY_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_CATEGORY_PARTIAL_UPDATE_FAILED =
  "API_V1_CATEGORY_PARTIAL_UPDATE_FAILED"
export const API_V1_CATEGORY_DELETE = "API_V1_CATEGORY_DELETE"
export const API_V1_CATEGORY_DELETE_SUCCEEDED =
  "API_V1_CATEGORY_DELETE_SUCCEEDED"
export const API_V1_CATEGORY_DELETE_FAILED = "API_V1_CATEGORY_DELETE_FAILED"
export const API_V1_COURSE_LIST = "API_V1_COURSE_LIST"
export const API_V1_COURSE_LIST_SUCCEEDED = "API_V1_COURSE_LIST_SUCCEEDED"
export const API_V1_COURSE_LIST_FAILED = "API_V1_COURSE_LIST_FAILED"
export const API_V1_COURSE_CREATE = "API_V1_COURSE_CREATE"
export const API_V1_COURSE_CREATE_SUCCEEDED = "API_V1_COURSE_CREATE_SUCCEEDED"
export const API_V1_COURSE_CREATE_FAILED = "API_V1_COURSE_CREATE_FAILED"
export const API_V1_COURSE_READ = "API_V1_COURSE_READ"
export const API_V1_COURSE_READ_SUCCEEDED = "API_V1_COURSE_READ_SUCCEEDED"
export const API_V1_COURSE_READ_FAILED = "API_V1_COURSE_READ_FAILED"
export const API_V1_COURSE_UPDATE = "API_V1_COURSE_UPDATE"
export const API_V1_COURSE_UPDATE_SUCCEEDED = "API_V1_COURSE_UPDATE_SUCCEEDED"
export const API_V1_COURSE_UPDATE_FAILED = "API_V1_COURSE_UPDATE_FAILED"
export const API_V1_COURSE_PARTIAL_UPDATE = "API_V1_COURSE_PARTIAL_UPDATE"
export const API_V1_COURSE_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_COURSE_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_COURSE_PARTIAL_UPDATE_FAILED =
  "API_V1_COURSE_PARTIAL_UPDATE_FAILED"
export const API_V1_COURSE_DELETE = "API_V1_COURSE_DELETE"
export const API_V1_COURSE_DELETE_SUCCEEDED = "API_V1_COURSE_DELETE_SUCCEEDED"
export const API_V1_COURSE_DELETE_FAILED = "API_V1_COURSE_DELETE_FAILED"
export const API_V1_CUSTOMTEXT_LIST = "API_V1_CUSTOMTEXT_LIST"
export const API_V1_CUSTOMTEXT_LIST_SUCCEEDED =
  "API_V1_CUSTOMTEXT_LIST_SUCCEEDED"
export const API_V1_CUSTOMTEXT_LIST_FAILED = "API_V1_CUSTOMTEXT_LIST_FAILED"
export const API_V1_CUSTOMTEXT_READ = "API_V1_CUSTOMTEXT_READ"
export const API_V1_CUSTOMTEXT_READ_SUCCEEDED =
  "API_V1_CUSTOMTEXT_READ_SUCCEEDED"
export const API_V1_CUSTOMTEXT_READ_FAILED = "API_V1_CUSTOMTEXT_READ_FAILED"
export const API_V1_CUSTOMTEXT_UPDATE = "API_V1_CUSTOMTEXT_UPDATE"
export const API_V1_CUSTOMTEXT_UPDATE_SUCCEEDED =
  "API_V1_CUSTOMTEXT_UPDATE_SUCCEEDED"
export const API_V1_CUSTOMTEXT_UPDATE_FAILED = "API_V1_CUSTOMTEXT_UPDATE_FAILED"
export const API_V1_CUSTOMTEXT_PARTIAL_UPDATE =
  "API_V1_CUSTOMTEXT_PARTIAL_UPDATE"
export const API_V1_CUSTOMTEXT_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_CUSTOMTEXT_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_CUSTOMTEXT_PARTIAL_UPDATE_FAILED =
  "API_V1_CUSTOMTEXT_PARTIAL_UPDATE_FAILED"
export const API_V1_ENROLLMENT_LIST = "API_V1_ENROLLMENT_LIST"
export const API_V1_ENROLLMENT_LIST_SUCCEEDED =
  "API_V1_ENROLLMENT_LIST_SUCCEEDED"
export const API_V1_ENROLLMENT_LIST_FAILED = "API_V1_ENROLLMENT_LIST_FAILED"
export const API_V1_ENROLLMENT_CREATE = "API_V1_ENROLLMENT_CREATE"
export const API_V1_ENROLLMENT_CREATE_SUCCEEDED =
  "API_V1_ENROLLMENT_CREATE_SUCCEEDED"
export const API_V1_ENROLLMENT_CREATE_FAILED = "API_V1_ENROLLMENT_CREATE_FAILED"
export const API_V1_ENROLLMENT_READ = "API_V1_ENROLLMENT_READ"
export const API_V1_ENROLLMENT_READ_SUCCEEDED =
  "API_V1_ENROLLMENT_READ_SUCCEEDED"
export const API_V1_ENROLLMENT_READ_FAILED = "API_V1_ENROLLMENT_READ_FAILED"
export const API_V1_ENROLLMENT_UPDATE = "API_V1_ENROLLMENT_UPDATE"
export const API_V1_ENROLLMENT_UPDATE_SUCCEEDED =
  "API_V1_ENROLLMENT_UPDATE_SUCCEEDED"
export const API_V1_ENROLLMENT_UPDATE_FAILED = "API_V1_ENROLLMENT_UPDATE_FAILED"
export const API_V1_ENROLLMENT_PARTIAL_UPDATE =
  "API_V1_ENROLLMENT_PARTIAL_UPDATE"
export const API_V1_ENROLLMENT_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_ENROLLMENT_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_ENROLLMENT_PARTIAL_UPDATE_FAILED =
  "API_V1_ENROLLMENT_PARTIAL_UPDATE_FAILED"
export const API_V1_ENROLLMENT_DELETE = "API_V1_ENROLLMENT_DELETE"
export const API_V1_ENROLLMENT_DELETE_SUCCEEDED =
  "API_V1_ENROLLMENT_DELETE_SUCCEEDED"
export const API_V1_ENROLLMENT_DELETE_FAILED = "API_V1_ENROLLMENT_DELETE_FAILED"
export const API_V1_EVENT_LIST = "API_V1_EVENT_LIST"
export const API_V1_EVENT_LIST_SUCCEEDED = "API_V1_EVENT_LIST_SUCCEEDED"
export const API_V1_EVENT_LIST_FAILED = "API_V1_EVENT_LIST_FAILED"
export const API_V1_EVENT_CREATE = "API_V1_EVENT_CREATE"
export const API_V1_EVENT_CREATE_SUCCEEDED = "API_V1_EVENT_CREATE_SUCCEEDED"
export const API_V1_EVENT_CREATE_FAILED = "API_V1_EVENT_CREATE_FAILED"
export const API_V1_EVENT_READ = "API_V1_EVENT_READ"
export const API_V1_EVENT_READ_SUCCEEDED = "API_V1_EVENT_READ_SUCCEEDED"
export const API_V1_EVENT_READ_FAILED = "API_V1_EVENT_READ_FAILED"
export const API_V1_EVENT_UPDATE = "API_V1_EVENT_UPDATE"
export const API_V1_EVENT_UPDATE_SUCCEEDED = "API_V1_EVENT_UPDATE_SUCCEEDED"
export const API_V1_EVENT_UPDATE_FAILED = "API_V1_EVENT_UPDATE_FAILED"
export const API_V1_EVENT_PARTIAL_UPDATE = "API_V1_EVENT_PARTIAL_UPDATE"
export const API_V1_EVENT_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_EVENT_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_EVENT_PARTIAL_UPDATE_FAILED =
  "API_V1_EVENT_PARTIAL_UPDATE_FAILED"
export const API_V1_EVENT_DELETE = "API_V1_EVENT_DELETE"
export const API_V1_EVENT_DELETE_SUCCEEDED = "API_V1_EVENT_DELETE_SUCCEEDED"
export const API_V1_EVENT_DELETE_FAILED = "API_V1_EVENT_DELETE_FAILED"
export const API_V1_GROUP_LIST = "API_V1_GROUP_LIST"
export const API_V1_GROUP_LIST_SUCCEEDED = "API_V1_GROUP_LIST_SUCCEEDED"
export const API_V1_GROUP_LIST_FAILED = "API_V1_GROUP_LIST_FAILED"
export const API_V1_GROUP_CREATE = "API_V1_GROUP_CREATE"
export const API_V1_GROUP_CREATE_SUCCEEDED = "API_V1_GROUP_CREATE_SUCCEEDED"
export const API_V1_GROUP_CREATE_FAILED = "API_V1_GROUP_CREATE_FAILED"
export const API_V1_GROUP_READ = "API_V1_GROUP_READ"
export const API_V1_GROUP_READ_SUCCEEDED = "API_V1_GROUP_READ_SUCCEEDED"
export const API_V1_GROUP_READ_FAILED = "API_V1_GROUP_READ_FAILED"
export const API_V1_GROUP_UPDATE = "API_V1_GROUP_UPDATE"
export const API_V1_GROUP_UPDATE_SUCCEEDED = "API_V1_GROUP_UPDATE_SUCCEEDED"
export const API_V1_GROUP_UPDATE_FAILED = "API_V1_GROUP_UPDATE_FAILED"
export const API_V1_GROUP_PARTIAL_UPDATE = "API_V1_GROUP_PARTIAL_UPDATE"
export const API_V1_GROUP_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_GROUP_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_GROUP_PARTIAL_UPDATE_FAILED =
  "API_V1_GROUP_PARTIAL_UPDATE_FAILED"
export const API_V1_GROUP_DELETE = "API_V1_GROUP_DELETE"
export const API_V1_GROUP_DELETE_SUCCEEDED = "API_V1_GROUP_DELETE_SUCCEEDED"
export const API_V1_GROUP_DELETE_FAILED = "API_V1_GROUP_DELETE_FAILED"
export const API_V1_HOMEPAGE_LIST = "API_V1_HOMEPAGE_LIST"
export const API_V1_HOMEPAGE_LIST_SUCCEEDED = "API_V1_HOMEPAGE_LIST_SUCCEEDED"
export const API_V1_HOMEPAGE_LIST_FAILED = "API_V1_HOMEPAGE_LIST_FAILED"
export const API_V1_HOMEPAGE_READ = "API_V1_HOMEPAGE_READ"
export const API_V1_HOMEPAGE_READ_SUCCEEDED = "API_V1_HOMEPAGE_READ_SUCCEEDED"
export const API_V1_HOMEPAGE_READ_FAILED = "API_V1_HOMEPAGE_READ_FAILED"
export const API_V1_HOMEPAGE_UPDATE = "API_V1_HOMEPAGE_UPDATE"
export const API_V1_HOMEPAGE_UPDATE_SUCCEEDED =
  "API_V1_HOMEPAGE_UPDATE_SUCCEEDED"
export const API_V1_HOMEPAGE_UPDATE_FAILED = "API_V1_HOMEPAGE_UPDATE_FAILED"
export const API_V1_HOMEPAGE_PARTIAL_UPDATE = "API_V1_HOMEPAGE_PARTIAL_UPDATE"
export const API_V1_HOMEPAGE_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_HOMEPAGE_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_HOMEPAGE_PARTIAL_UPDATE_FAILED =
  "API_V1_HOMEPAGE_PARTIAL_UPDATE_FAILED"
export const API_V1_LESSON_LIST = "API_V1_LESSON_LIST"
export const API_V1_LESSON_LIST_SUCCEEDED = "API_V1_LESSON_LIST_SUCCEEDED"
export const API_V1_LESSON_LIST_FAILED = "API_V1_LESSON_LIST_FAILED"
export const API_V1_LESSON_CREATE = "API_V1_LESSON_CREATE"
export const API_V1_LESSON_CREATE_SUCCEEDED = "API_V1_LESSON_CREATE_SUCCEEDED"
export const API_V1_LESSON_CREATE_FAILED = "API_V1_LESSON_CREATE_FAILED"
export const API_V1_LESSON_READ = "API_V1_LESSON_READ"
export const API_V1_LESSON_READ_SUCCEEDED = "API_V1_LESSON_READ_SUCCEEDED"
export const API_V1_LESSON_READ_FAILED = "API_V1_LESSON_READ_FAILED"
export const API_V1_LESSON_UPDATE = "API_V1_LESSON_UPDATE"
export const API_V1_LESSON_UPDATE_SUCCEEDED = "API_V1_LESSON_UPDATE_SUCCEEDED"
export const API_V1_LESSON_UPDATE_FAILED = "API_V1_LESSON_UPDATE_FAILED"
export const API_V1_LESSON_PARTIAL_UPDATE = "API_V1_LESSON_PARTIAL_UPDATE"
export const API_V1_LESSON_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_LESSON_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_LESSON_PARTIAL_UPDATE_FAILED =
  "API_V1_LESSON_PARTIAL_UPDATE_FAILED"
export const API_V1_LESSON_DELETE = "API_V1_LESSON_DELETE"
export const API_V1_LESSON_DELETE_SUCCEEDED = "API_V1_LESSON_DELETE_SUCCEEDED"
export const API_V1_LESSON_DELETE_FAILED = "API_V1_LESSON_DELETE_FAILED"
export const API_V1_LOGIN_CREATE = "API_V1_LOGIN_CREATE"
export const API_V1_LOGIN_CREATE_SUCCEEDED = "API_V1_LOGIN_CREATE_SUCCEEDED"
export const API_V1_LOGIN_CREATE_FAILED = "API_V1_LOGIN_CREATE_FAILED"
export const API_V1_MODULE_LIST = "API_V1_MODULE_LIST"
export const API_V1_MODULE_LIST_SUCCEEDED = "API_V1_MODULE_LIST_SUCCEEDED"
export const API_V1_MODULE_LIST_FAILED = "API_V1_MODULE_LIST_FAILED"
export const API_V1_MODULE_CREATE = "API_V1_MODULE_CREATE"
export const API_V1_MODULE_CREATE_SUCCEEDED = "API_V1_MODULE_CREATE_SUCCEEDED"
export const API_V1_MODULE_CREATE_FAILED = "API_V1_MODULE_CREATE_FAILED"
export const API_V1_MODULE_READ = "API_V1_MODULE_READ"
export const API_V1_MODULE_READ_SUCCEEDED = "API_V1_MODULE_READ_SUCCEEDED"
export const API_V1_MODULE_READ_FAILED = "API_V1_MODULE_READ_FAILED"
export const API_V1_MODULE_UPDATE = "API_V1_MODULE_UPDATE"
export const API_V1_MODULE_UPDATE_SUCCEEDED = "API_V1_MODULE_UPDATE_SUCCEEDED"
export const API_V1_MODULE_UPDATE_FAILED = "API_V1_MODULE_UPDATE_FAILED"
export const API_V1_MODULE_PARTIAL_UPDATE = "API_V1_MODULE_PARTIAL_UPDATE"
export const API_V1_MODULE_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_MODULE_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_MODULE_PARTIAL_UPDATE_FAILED =
  "API_V1_MODULE_PARTIAL_UPDATE_FAILED"
export const API_V1_MODULE_DELETE = "API_V1_MODULE_DELETE"
export const API_V1_MODULE_DELETE_SUCCEEDED = "API_V1_MODULE_DELETE_SUCCEEDED"
export const API_V1_MODULE_DELETE_FAILED = "API_V1_MODULE_DELETE_FAILED"
export const API_V1_PAYMENTMETHOD_LIST = "API_V1_PAYMENTMETHOD_LIST"
export const API_V1_PAYMENTMETHOD_LIST_SUCCEEDED =
  "API_V1_PAYMENTMETHOD_LIST_SUCCEEDED"
export const API_V1_PAYMENTMETHOD_LIST_FAILED =
  "API_V1_PAYMENTMETHOD_LIST_FAILED"
export const API_V1_PAYMENTMETHOD_CREATE = "API_V1_PAYMENTMETHOD_CREATE"
export const API_V1_PAYMENTMETHOD_CREATE_SUCCEEDED =
  "API_V1_PAYMENTMETHOD_CREATE_SUCCEEDED"
export const API_V1_PAYMENTMETHOD_CREATE_FAILED =
  "API_V1_PAYMENTMETHOD_CREATE_FAILED"
export const API_V1_PAYMENTMETHOD_READ = "API_V1_PAYMENTMETHOD_READ"
export const API_V1_PAYMENTMETHOD_READ_SUCCEEDED =
  "API_V1_PAYMENTMETHOD_READ_SUCCEEDED"
export const API_V1_PAYMENTMETHOD_READ_FAILED =
  "API_V1_PAYMENTMETHOD_READ_FAILED"
export const API_V1_PAYMENTMETHOD_UPDATE = "API_V1_PAYMENTMETHOD_UPDATE"
export const API_V1_PAYMENTMETHOD_UPDATE_SUCCEEDED =
  "API_V1_PAYMENTMETHOD_UPDATE_SUCCEEDED"
export const API_V1_PAYMENTMETHOD_UPDATE_FAILED =
  "API_V1_PAYMENTMETHOD_UPDATE_FAILED"
export const API_V1_PAYMENTMETHOD_PARTIAL_UPDATE =
  "API_V1_PAYMENTMETHOD_PARTIAL_UPDATE"
export const API_V1_PAYMENTMETHOD_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_PAYMENTMETHOD_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_PAYMENTMETHOD_PARTIAL_UPDATE_FAILED =
  "API_V1_PAYMENTMETHOD_PARTIAL_UPDATE_FAILED"
export const API_V1_PAYMENTMETHOD_DELETE = "API_V1_PAYMENTMETHOD_DELETE"
export const API_V1_PAYMENTMETHOD_DELETE_SUCCEEDED =
  "API_V1_PAYMENTMETHOD_DELETE_SUCCEEDED"
export const API_V1_PAYMENTMETHOD_DELETE_FAILED =
  "API_V1_PAYMENTMETHOD_DELETE_FAILED"
export const API_V1_RECORDING_LIST = "API_V1_RECORDING_LIST"
export const API_V1_RECORDING_LIST_SUCCEEDED = "API_V1_RECORDING_LIST_SUCCEEDED"
export const API_V1_RECORDING_LIST_FAILED = "API_V1_RECORDING_LIST_FAILED"
export const API_V1_RECORDING_CREATE = "API_V1_RECORDING_CREATE"
export const API_V1_RECORDING_CREATE_SUCCEEDED =
  "API_V1_RECORDING_CREATE_SUCCEEDED"
export const API_V1_RECORDING_CREATE_FAILED = "API_V1_RECORDING_CREATE_FAILED"
export const API_V1_RECORDING_READ = "API_V1_RECORDING_READ"
export const API_V1_RECORDING_READ_SUCCEEDED = "API_V1_RECORDING_READ_SUCCEEDED"
export const API_V1_RECORDING_READ_FAILED = "API_V1_RECORDING_READ_FAILED"
export const API_V1_RECORDING_UPDATE = "API_V1_RECORDING_UPDATE"
export const API_V1_RECORDING_UPDATE_SUCCEEDED =
  "API_V1_RECORDING_UPDATE_SUCCEEDED"
export const API_V1_RECORDING_UPDATE_FAILED = "API_V1_RECORDING_UPDATE_FAILED"
export const API_V1_RECORDING_PARTIAL_UPDATE = "API_V1_RECORDING_PARTIAL_UPDATE"
export const API_V1_RECORDING_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_RECORDING_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_RECORDING_PARTIAL_UPDATE_FAILED =
  "API_V1_RECORDING_PARTIAL_UPDATE_FAILED"
export const API_V1_RECORDING_DELETE = "API_V1_RECORDING_DELETE"
export const API_V1_RECORDING_DELETE_SUCCEEDED =
  "API_V1_RECORDING_DELETE_SUCCEEDED"
export const API_V1_RECORDING_DELETE_FAILED = "API_V1_RECORDING_DELETE_FAILED"
export const API_V1_SIGNUP_CREATE = "API_V1_SIGNUP_CREATE"
export const API_V1_SIGNUP_CREATE_SUCCEEDED = "API_V1_SIGNUP_CREATE_SUCCEEDED"
export const API_V1_SIGNUP_CREATE_FAILED = "API_V1_SIGNUP_CREATE_FAILED"
export const API_V1_SUBSCRIPTION_LIST = "API_V1_SUBSCRIPTION_LIST"
export const API_V1_SUBSCRIPTION_LIST_SUCCEEDED =
  "API_V1_SUBSCRIPTION_LIST_SUCCEEDED"
export const API_V1_SUBSCRIPTION_LIST_FAILED = "API_V1_SUBSCRIPTION_LIST_FAILED"
export const API_V1_SUBSCRIPTION_CREATE = "API_V1_SUBSCRIPTION_CREATE"
export const API_V1_SUBSCRIPTION_CREATE_SUCCEEDED =
  "API_V1_SUBSCRIPTION_CREATE_SUCCEEDED"
export const API_V1_SUBSCRIPTION_CREATE_FAILED =
  "API_V1_SUBSCRIPTION_CREATE_FAILED"
export const API_V1_SUBSCRIPTION_READ = "API_V1_SUBSCRIPTION_READ"
export const API_V1_SUBSCRIPTION_READ_SUCCEEDED =
  "API_V1_SUBSCRIPTION_READ_SUCCEEDED"
export const API_V1_SUBSCRIPTION_READ_FAILED = "API_V1_SUBSCRIPTION_READ_FAILED"
export const API_V1_SUBSCRIPTION_UPDATE = "API_V1_SUBSCRIPTION_UPDATE"
export const API_V1_SUBSCRIPTION_UPDATE_SUCCEEDED =
  "API_V1_SUBSCRIPTION_UPDATE_SUCCEEDED"
export const API_V1_SUBSCRIPTION_UPDATE_FAILED =
  "API_V1_SUBSCRIPTION_UPDATE_FAILED"
export const API_V1_SUBSCRIPTION_PARTIAL_UPDATE =
  "API_V1_SUBSCRIPTION_PARTIAL_UPDATE"
export const API_V1_SUBSCRIPTION_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_SUBSCRIPTION_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_SUBSCRIPTION_PARTIAL_UPDATE_FAILED =
  "API_V1_SUBSCRIPTION_PARTIAL_UPDATE_FAILED"
export const API_V1_SUBSCRIPTION_DELETE = "API_V1_SUBSCRIPTION_DELETE"
export const API_V1_SUBSCRIPTION_DELETE_SUCCEEDED =
  "API_V1_SUBSCRIPTION_DELETE_SUCCEEDED"
export const API_V1_SUBSCRIPTION_DELETE_FAILED =
  "API_V1_SUBSCRIPTION_DELETE_FAILED"
export const API_V1_SUBSCRIPTIONTYPE_LIST = "API_V1_SUBSCRIPTIONTYPE_LIST"
export const API_V1_SUBSCRIPTIONTYPE_LIST_SUCCEEDED =
  "API_V1_SUBSCRIPTIONTYPE_LIST_SUCCEEDED"
export const API_V1_SUBSCRIPTIONTYPE_LIST_FAILED =
  "API_V1_SUBSCRIPTIONTYPE_LIST_FAILED"
export const API_V1_SUBSCRIPTIONTYPE_CREATE = "API_V1_SUBSCRIPTIONTYPE_CREATE"
export const API_V1_SUBSCRIPTIONTYPE_CREATE_SUCCEEDED =
  "API_V1_SUBSCRIPTIONTYPE_CREATE_SUCCEEDED"
export const API_V1_SUBSCRIPTIONTYPE_CREATE_FAILED =
  "API_V1_SUBSCRIPTIONTYPE_CREATE_FAILED"
export const API_V1_SUBSCRIPTIONTYPE_READ = "API_V1_SUBSCRIPTIONTYPE_READ"
export const API_V1_SUBSCRIPTIONTYPE_READ_SUCCEEDED =
  "API_V1_SUBSCRIPTIONTYPE_READ_SUCCEEDED"
export const API_V1_SUBSCRIPTIONTYPE_READ_FAILED =
  "API_V1_SUBSCRIPTIONTYPE_READ_FAILED"
export const API_V1_SUBSCRIPTIONTYPE_UPDATE = "API_V1_SUBSCRIPTIONTYPE_UPDATE"
export const API_V1_SUBSCRIPTIONTYPE_UPDATE_SUCCEEDED =
  "API_V1_SUBSCRIPTIONTYPE_UPDATE_SUCCEEDED"
export const API_V1_SUBSCRIPTIONTYPE_UPDATE_FAILED =
  "API_V1_SUBSCRIPTIONTYPE_UPDATE_FAILED"
export const API_V1_SUBSCRIPTIONTYPE_PARTIAL_UPDATE =
  "API_V1_SUBSCRIPTIONTYPE_PARTIAL_UPDATE"
export const API_V1_SUBSCRIPTIONTYPE_PARTIAL_UPDATE_SUCCEEDED =
  "API_V1_SUBSCRIPTIONTYPE_PARTIAL_UPDATE_SUCCEEDED"
export const API_V1_SUBSCRIPTIONTYPE_PARTIAL_UPDATE_FAILED =
  "API_V1_SUBSCRIPTIONTYPE_PARTIAL_UPDATE_FAILED"
export const API_V1_SUBSCRIPTIONTYPE_DELETE = "API_V1_SUBSCRIPTIONTYPE_DELETE"
export const API_V1_SUBSCRIPTIONTYPE_DELETE_SUCCEEDED =
  "API_V1_SUBSCRIPTIONTYPE_DELETE_SUCCEEDED"
export const API_V1_SUBSCRIPTIONTYPE_DELETE_FAILED =
  "API_V1_SUBSCRIPTIONTYPE_DELETE_FAILED"
export const REST_AUTH_LOGIN_CREATE = "REST_AUTH_LOGIN_CREATE"
export const REST_AUTH_LOGIN_CREATE_SUCCEEDED =
  "REST_AUTH_LOGIN_CREATE_SUCCEEDED"
export const REST_AUTH_LOGIN_CREATE_FAILED = "REST_AUTH_LOGIN_CREATE_FAILED"
export const REST_AUTH_LOGOUT_LIST = "REST_AUTH_LOGOUT_LIST"
export const REST_AUTH_LOGOUT_LIST_SUCCEEDED = "REST_AUTH_LOGOUT_LIST_SUCCEEDED"
export const REST_AUTH_LOGOUT_LIST_FAILED = "REST_AUTH_LOGOUT_LIST_FAILED"
export const REST_AUTH_LOGOUT_CREATE = "REST_AUTH_LOGOUT_CREATE"
export const REST_AUTH_LOGOUT_CREATE_SUCCEEDED =
  "REST_AUTH_LOGOUT_CREATE_SUCCEEDED"
export const REST_AUTH_LOGOUT_CREATE_FAILED = "REST_AUTH_LOGOUT_CREATE_FAILED"
export const REST_AUTH_PASSWORD_CHANGE_CREATE =
  "REST_AUTH_PASSWORD_CHANGE_CREATE"
export const REST_AUTH_PASSWORD_CHANGE_CREATE_SUCCEEDED =
  "REST_AUTH_PASSWORD_CHANGE_CREATE_SUCCEEDED"
export const REST_AUTH_PASSWORD_CHANGE_CREATE_FAILED =
  "REST_AUTH_PASSWORD_CHANGE_CREATE_FAILED"
export const REST_AUTH_PASSWORD_RESET_CREATE = "REST_AUTH_PASSWORD_RESET_CREATE"
export const REST_AUTH_PASSWORD_RESET_CREATE_SUCCEEDED =
  "REST_AUTH_PASSWORD_RESET_CREATE_SUCCEEDED"
export const REST_AUTH_PASSWORD_RESET_CREATE_FAILED =
  "REST_AUTH_PASSWORD_RESET_CREATE_FAILED"
export const REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE =
  "REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE"
export const REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_SUCCEEDED =
  "REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_SUCCEEDED"
export const REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_FAILED =
  "REST_AUTH_PASSWORD_RESET_CONFIRM_CREATE_FAILED"
export const REST_AUTH_REGISTRATION_CREATE = "REST_AUTH_REGISTRATION_CREATE"
export const REST_AUTH_REGISTRATION_CREATE_SUCCEEDED =
  "REST_AUTH_REGISTRATION_CREATE_SUCCEEDED"
export const REST_AUTH_REGISTRATION_CREATE_FAILED =
  "REST_AUTH_REGISTRATION_CREATE_FAILED"
export const REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE =
  "REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE"
export const REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_SUCCEEDED =
  "REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_SUCCEEDED"
export const REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_FAILED =
  "REST_AUTH_REGISTRATION_VERIFY_EMAIL_CREATE_FAILED"
export const REST_AUTH_USER_READ = "REST_AUTH_USER_READ"
export const REST_AUTH_USER_READ_SUCCEEDED = "REST_AUTH_USER_READ_SUCCEEDED"
export const REST_AUTH_USER_READ_FAILED = "REST_AUTH_USER_READ_FAILED"
export const REST_AUTH_USER_UPDATE = "REST_AUTH_USER_UPDATE"
export const REST_AUTH_USER_UPDATE_SUCCEEDED = "REST_AUTH_USER_UPDATE_SUCCEEDED"
export const REST_AUTH_USER_UPDATE_FAILED = "REST_AUTH_USER_UPDATE_FAILED"
export const REST_AUTH_USER_PARTIAL_UPDATE = "REST_AUTH_USER_PARTIAL_UPDATE"
export const REST_AUTH_USER_PARTIAL_UPDATE_SUCCEEDED =
  "REST_AUTH_USER_PARTIAL_UPDATE_SUCCEEDED"
export const REST_AUTH_USER_PARTIAL_UPDATE_FAILED =
  "REST_AUTH_USER_PARTIAL_UPDATE_FAILED"
